/*
 * @Description: 国家地图区划中英文对照名称
 * @Author: chenfengtao
 * @Date: 2022-08-29 09:11:02
 * @LastEditors: chenfengtao
 * @LastEditTime: 2022-08-29 10:48:49
 */
export const mapLabels = {
  russia: {
    'Moscow City': '莫斯科直辖市',
    Belgorod: '别尔哥罗德州',
    Bryansk: '布良斯克州',
    Ivanovo: '伊万诺沃州',
    Kaluga: '卡卢加州',
    Kostroma: '科斯特罗马州',
    Kursk: '库尔斯克州',
    Lipetsk: '利佩茨克洲',
    Moskva: '莫斯科州',
    Orel: '奥廖尔州',
    Ryazan: '梁赞州',
    Smolensk: '斯摩棱斯克州',
    Tambov: '坦波夫州',
    Tver: '特维尔州',
    Tula: '图拉州',
    Vladimir: '弗拉基米尔州',
    Voronezh: '沃罗涅日州',
    Yaroslavl: '雅罗斯拉夫尔州',
    'Saint Petersburg City': '圣彼得堡直辖市',
    "Arkhangel'sk": '阿尔汉格尔斯克州',
    Nenets: '涅涅茨自治区',
    Kaliningrad: '加里宁格勒州',
    Karelia: '卡累利阿共和国',
    Komi: '科米共和国',
    Murmansk: '摩尔曼斯克州',
    Novgorod: '诺夫哥罗德州',
    Pskov: '普斯科夫州',
    Leningrad: '列宁格勒州',
    Vologda: '沃洛格达州',
    Adygey: '阿迪格共和国',
    Astrakhan: '阿斯特拉罕州',
    Kalmyk: '卡尔梅克共和国',
    Krasnodar: '克拉斯诺达尔边疆区',
    Rostov: '罗斯托夫州',
    Volgograd: '伏尔加格勒州',
    Sevastolol: '塞瓦斯托波尔直辖市',
    Crimea: '克里米亚共和国',
    Dagestan: '达吉斯坦共和国',
    Ingush: '印古什共和国',
    'Kabardin-Balkar': '卡巴尔达-巴尔卡尔共和国',
    'Karachay-Cherkess': '卡拉恰伊-切尔克斯共和国',
    Stavropol: '斯塔夫罗波尔边疆区',
    'North Ossetia': '北奥塞梯-阿兰共和国',
    Chechnya: '车臣共和国',
    Bashkortostan: '巴什科尔托斯坦共和国（巴什基尔）',
    Chuvash: '楚瓦什共和国',
    Kirov: '基洛夫州',
    'Mariy-El': '马里埃尔共和国',
    Mordovia: '莫尔多瓦共和国',
    Nizhegorod: '下诺夫哥罗德州',
    Orenburg: '奥伦堡州',
    Penza: '奔萨州',
    Perm: '彼尔姆边疆区',
    Samara: '萨马拉州',
    Saratov: '萨拉托夫州',
    Tatarstan: '鞑靼斯坦共和国',
    Udmurt: '乌德穆尔特共和国',
    "Ul'yanovsk": '乌里扬诺夫斯克州',
    Kurgan: '库尔干州',
    Sverdlovsk: '斯维尔德洛夫斯克州',
    Tyumen: '秋明州',
    'Khanty-Mansiy': '汉特-曼西自治区',
    'Yamal-Nenets': '亚马尔-涅涅茨自治区',
    Chelyabinsk: '车里雅宾斯克州',
    'Gorno-Altay': '阿尔泰共和国',
    Altay: '阿尔泰边疆区',
    Irkutsk: '雅库茨克州',
    Khakass: '哈卡斯共和国',
    Kemerovo: '科麦罗沃州',
    Krasnoyarsk: '克拉斯诺亚尔斯克边疆区',
    Novosibirsk: '新西伯利亚州',
    Omsk: '鄂木斯克州',
    Tomsk: '托木斯克州',
    Tuva: '图瓦共和国',
    Amur: '阿穆尔州',
    Yevrey: '犹太自治州',
    Kamchatka: '堪察加边疆区',
    Khabarovsk: '哈巴罗夫斯克边疆区',
    Magadan: '马加丹州',
    Chukot: '楚科奇自治区',
    "Primor'ye": '滨海边疆区',
    Sakha: '萨哈（雅库特）共和国',
    Sakhalin: '萨哈林州',
    "Zabaykal'ye": '后贝加尔边疆区',
    Buryat: '布里亚特共和国',
  },
  india: {
    'Andhra Pradesh': '安得拉邦',
    Manipur: '曼尼普尔邦',
    Punjab: '旁遮普邦',
    Rajasthan: '拉贾斯坦邦',
    'West Bengal': '西孟加拉邦',
    'Himachal Pradesh': '喜马偕尔邦',
    Karnataka: '卡纳塔克邦',
    Maharashtra: '马哈拉施特拉邦',
    Assam: '阿萨姆邦',
    Meghalaya: '梅加拉亚邦',
    Mizoram: '米佐拉姆邦',
    Nagaland: '那加兰邦',
    Bihar: '比哈尔邦',
    Kerala: '喀拉拉邦',
    Orissa: '奥里萨邦',
    'Madhya Pradesh': '中央邦',
    Chhattisgarh: '恰蒂斯加尔邦',
    Gujarat: '古吉拉特邦',
    Haryana: '哈里亚纳邦',
    'Jammu and Kashmir': '查谟-克什米尔邦',
    Goa: '果阿邦',
    Jharkhand: '贾坎德邦',
    Sikkim: '锡金邦',
    'Uttar Pradesh': '北方邦',
    Tripura: '特里普拉邦',
    Uttarakhand: '北阿坎德邦',
    'Tamil Nadu': '泰米尔纳德邦',
    Telangana: '特伦甘纳邦',
    Lakshadweep: '拉克沙群岛',
    Delhi: '新德里',
    Chandigarh: '昌迪加尔',
    Puducherry: '本地治里',
    'Daman and Diu': '达曼和第乌',
    'Dadra and Nagar Haveli': '达德拉·纳加尔哈维利',
    'Andaman and Nicobar': '安达曼-尼科巴群岛',
  },
  brazil: {
    Acre: '阿克里州',
    Alagoas: '阿拉戈斯',
    Amazonas: '亚马逊州',
    Amapá: '阿马帕',
    Bahia: '巴伊亚',
    Ceará: '塞阿拉',
    'Espírito Santo': '圣埃斯皮里图',
    Goiás: '戈亚斯',
    Maranhão: '马拉尼昂',
    'Mato Grosso': '马托格罗索',
    'Mato Grosso do Sul': '南马托格罗索',
    'Minas Gerais': '米纳斯吉拉斯',
    Pará: '帕拉',
    Paraíba: '帕拉伊巴',
    Paraná: '巴拉那',
    Pernambuco: '伯南布哥',
    Piauí: '皮奥伊',
    'Rio Grande do Norte': '北里奥格兰德',
    'Rio Grande do Sul': '南里奥格兰德',
    'Rio de Janeiro': '里约热内卢',
    Rondônia: '朗多尼亚',
    Roraima: '罗赖马州',
    'Santa Catarina': '圣卡塔琳娜',
    'São Paulo': '圣保罗',
    Sergipe: '塞尔希培',
    Tocantins: '托坎廷斯',
    'Distrito Federal': '巴西利亚联邦区',
  },
  'south-africa': {
    'Eastern Cape': '东开普省',
    'Western Cape': '西开普省',
    'Northern Cape': '北开普省',
    'KwaZulu-Natal': '夸祖鲁省/纳塔尔省',
    'Free State': '自由州省',
    'North West': '西北省',
    Limpopo: '林波波省',
    Mpumalanga: '姆普马兰加省',
    Gauteng: '豪登省',
    Pretoria: '行政首都比勒陀利亚',
    'Cape Town': '立法首都开普敦',
    Bloemfontein: '司法首都布隆方丹',
  },
  china: {
    河北省: 'Hebei',
    山西省: 'Shanxi',
    辽宁省: 'Liaoning',
    吉林省: 'Jilin Province',
    黑龙江省: 'Heilongjiang',
    江苏省: 'Jiangsu',
    浙江省: 'Zhejiang',
    安徽省: 'Anhui',
    福建省: 'Fujian',
    江西省: 'Jiangxi',
    山东省: 'Shandong',
    河南省: 'Henan',
    湖北省: 'Hubei',
    湖南省: 'Hunan',
    广东省: 'Guangdong',
    海南省: 'Hainan',
    四川省: 'Sichuan',
    贵州省: 'Guizhou',
    云南省: 'Yunnan',
    陕西省: 'Shaanxi',
    甘肃省: 'Gansu',
    青海省: 'Qinghai',
    台湾省: 'Taiwan',
    内蒙古自治区: 'Inner Mongolia',
    广西壮族自治区: 'GuangXi',
    西藏自治区: 'Xizang',
    宁夏回族自治区: 'Ningxia',
    新疆维吾尔自治区: 'Xinjiang',
    北京市: 'Beijing',
    天津市: 'Tianjin',
    上海市: 'Shanghai',
    重庆市: 'Chongqing',
    香港特别行政区: 'Hong Kong',
    澳门特别行政区: 'Macao',
  },
}
